// Code generated by nero, DO NOT EDIT.
package playerrepo

// Table is the database table
const Table = "players"

// Field is a Player field
type Field int

// String returns the string representation of the field
func (f Field) String() string {
	return [...]string{
		"invalid",
		"id",
		"email",
		"name",
		"age",
		"race",
		"updated_at",
		"created_at",
	}[f]
}

const (
	FieldID Field = iota + 1
	FieldEmail
	FieldName
	FieldAge
	FieldRace
	FieldUpdatedAt
	FieldCreatedAt
)
