// Code generated by nero, DO NOT EDIT.
package playerrepo

// Collection is the name of the collection
const Collection = "players"

// Column is a Player column
type Column int

// String returns the string representation of the Column
func (c Column) String() string {
	return [...]string{
		"id",
		"email",
		"name",
		"age",
		"race",
		"interests",
		"updated_at",
		"created_at",
	}[c]
}

const (
	ColumnID Column = iota
	ColumnEmail
	ColumnName
	ColumnAge
	ColumnRace
	ColumnInterests
	ColumnUpdatedAt
	ColumnCreatedAt
)
