// Code generated by nero, DO NOT EDIT.
package playerrepo

import (
	"time"

	"github.com/sf9v/nero/comparison"
	"github.com/sf9v/nero/test/integration/player"
)

// IDEq applies "equal" operator on "id" column
func IDEq(id string) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "id",
			Op:  comparison.Eq,
			Arg: id,
		})
	}
}

// IDNotEq applies "not equal" operator on "id" column
func IDNotEq(id string) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "id",
			Op:  comparison.NotEq,
			Arg: id,
		})
	}
}

// IDIn applies "in" operator on "id" column
func IDIn(ids ...string) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range ids {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "id",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// IDNotIn applies "not in" operator on "id" column
func IDNotIn(ids ...string) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range ids {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "id",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}

// EmailEq applies "equal" operator on "email" column
func EmailEq(email string) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "email",
			Op:  comparison.Eq,
			Arg: email,
		})
	}
}

// EmailNotEq applies "not equal" operator on "email" column
func EmailNotEq(email string) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "email",
			Op:  comparison.NotEq,
			Arg: email,
		})
	}
}

// EmailIn applies "in" operator on "email" column
func EmailIn(emails ...string) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range emails {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "email",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// EmailNotIn applies "not in" operator on "email" column
func EmailNotIn(emails ...string) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range emails {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "email",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}

// NameEq applies "equal" operator on "name" column
func NameEq(name string) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "name",
			Op:  comparison.Eq,
			Arg: name,
		})
	}
}

// NameNotEq applies "not equal" operator on "name" column
func NameNotEq(name string) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "name",
			Op:  comparison.NotEq,
			Arg: name,
		})
	}
}

// NameIn applies "in" operator on "name" column
func NameIn(names ...string) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range names {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "name",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// NameNotIn applies "not in" operator on "name" column
func NameNotIn(names ...string) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range names {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "name",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}

// AgeEq applies "equal" operator on "age" column
func AgeEq(age int) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.Eq,
			Arg: age,
		})
	}
}

// AgeNotEq applies "not equal" operator on "age" column
func AgeNotEq(age int) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.NotEq,
			Arg: age,
		})
	}
}

// AgeGt applies "greater than" operator on "age" column
func AgeGt(age int) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.Gt,
			Arg: age,
		})
	}
}

// AgeGtOrEq applies "greater than or equal" operator on "age" column
func AgeGtOrEq(age int) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.GtOrEq,
			Arg: age,
		})
	}
}

// AgeLt applies "less than" operator on "age" column
func AgeLt(age int) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.Lt,
			Arg: age,
		})
	}
}

// AgeLtOrEq applies "less than or equal" operator on "age" column
func AgeLtOrEq(age int) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.LtOrEq,
			Arg: age,
		})
	}
}

// AgeIn applies "in" operator on "age" column
func AgeIn(ages ...int) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range ages {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// AgeNotIn applies "not in" operator on "age" column
func AgeNotIn(ages ...int) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range ages {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "age",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}

// RaceEq applies "equal" operator on "race" column
func RaceEq(race player.Race) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "race",
			Op:  comparison.Eq,
			Arg: race,
		})
	}
}

// RaceNotEq applies "not equal" operator on "race" column
func RaceNotEq(race player.Race) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "race",
			Op:  comparison.NotEq,
			Arg: race,
		})
	}
}

// RaceIn applies "in" operator on "race" column
func RaceIn(races ...player.Race) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range races {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "race",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// RaceNotIn applies "not in" operator on "race" column
func RaceNotIn(races ...player.Race) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range races {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "race",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}

// UpdatedAtEq applies "equal" operator on "updated_at" column
func UpdatedAtEq(updatedAt *time.Time) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "updated_at",
			Op:  comparison.Eq,
			Arg: updatedAt,
		})
	}
}

// UpdatedAtNotEq applies "not equal" operator on "updated_at" column
func UpdatedAtNotEq(updatedAt *time.Time) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "updated_at",
			Op:  comparison.NotEq,
			Arg: updatedAt,
		})
	}
}

// UpdatedAtIsNull applies "is null" operator on "updated_at" column
func UpdatedAtIsNull() comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "updated_at",
			Op:  comparison.IsNull,
		})
	}
}

// UpdatedAtIsNotNull applies "is not null" operator on "updated_at" column
func UpdatedAtIsNotNull() comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "updated_at",
			Op:  comparison.IsNotNull,
		})
	}
}

// UpdatedAtIn applies "in" operator on "updated_at" column
func UpdatedAtIn(updatedAts ...*time.Time) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range updatedAts {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "updated_at",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// UpdatedAtNotIn applies "not in" operator on "updated_at" column
func UpdatedAtNotIn(updatedAts ...*time.Time) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range updatedAts {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "updated_at",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}

// CreatedAtEq applies "equal" operator on "created_at" column
func CreatedAtEq(createdAt *time.Time) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "created_at",
			Op:  comparison.Eq,
			Arg: createdAt,
		})
	}
}

// CreatedAtNotEq applies "not equal" operator on "created_at" column
func CreatedAtNotEq(createdAt *time.Time) comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "created_at",
			Op:  comparison.NotEq,
			Arg: createdAt,
		})
	}
}

// CreatedAtIsNull applies "is null" operator on "created_at" column
func CreatedAtIsNull() comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "created_at",
			Op:  comparison.IsNull,
		})
	}
}

// CreatedAtIsNotNull applies "is not null" operator on "created_at" column
func CreatedAtIsNotNull() comparison.PredFunc {
	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "created_at",
			Op:  comparison.IsNotNull,
		})
	}
}

// CreatedAtIn applies "in" operator on "created_at" column
func CreatedAtIn(createdAts ...*time.Time) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range createdAts {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "created_at",
			Op:  comparison.In,
			Arg: args,
		})
	}
}

// CreatedAtNotIn applies "not in" operator on "created_at" column
func CreatedAtNotIn(createdAts ...*time.Time) comparison.PredFunc {
	args := []interface{}{}
	for _, v := range createdAts {
		args = append(args, v)
	}

	return func(preds []*comparison.Predicate) []*comparison.Predicate {
		return append(preds, &comparison.Predicate{
			Col: "created_at",
			Op:  comparison.NotIn,
			Arg: args,
		})
	}
}
