// Code generated by nero, DO NOT EDIT.
package playerrepo

import (
	"github.com/sf9v/nero/sort"
)

// Asc sorts in ascending order
func Asc(col Column) sort.SortFunc {
	return func(sorts []*sort.Sort) []*sort.Sort {
		return append(sorts, &sort.Sort{
			Col:       col.String(),
			Direction: sort.Asc,
		})
	}
}

// Desc sorts in descending order
func Desc(col Column) sort.SortFunc {
	return func(sorts []*sort.Sort) []*sort.Sort {
		return append(sorts, &sort.Sort{
			Col:       col.String(),
			Direction: sort.Desc,
		})
	}
}
