// Code generated by nero, DO NOT EDIT.
package playerrepo

import (
	"github.com/stevenferrer/nero/sorting"
)

// Asc ascending sort direction
func Asc(fields ...Field) sorting.Func {
	return func(sortings sorting.Sortings) sorting.Sortings {
		for _, field := range fields {
			sortings = append(sortings, sorting.Sorting{
				Field:     field.String(),
				Direction: sorting.Asc,
			})
		}

		return sortings
	}
}

// Desc descending sort direction
func Desc(fields ...Field) sorting.Func {
	return func(sortings sorting.Sortings) sorting.Sortings {
		for _, field := range fields {
			sortings = append(sortings, sorting.Sorting{
				Field:     field.String(),
				Direction: sorting.Desc,
			})
		}

		return sortings
	}
}
