// Code generated by nero, DO NOT EDIT.
package repository

// Collection is the name of the collection
const Collection = "users"

// Column is a User column
type Column int

// String implements Stringer
func (c Column) String() string {
	return [...]string{
		"id",
		"uid",
		"email",
		"name",
		"age",
		"group",
		"kv",
		"tags",
		"updated_at",
		"created_at",
	}[c]
}

const (
	ColumnID Column = iota
	ColumnUID
	ColumnEmail
	ColumnName
	ColumnAge
	ColumnGroup
	ColumnKv
	ColumnTags
	ColumnUpdatedAt
	ColumnCreatedAt
)
