// Code generated by nero, DO NOT EDIT.
package repository

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"
	"reflect"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/lib/pq"
	"github.com/pkg/errors"
	"github.com/sf9v/nero"
	"github.com/sf9v/nero/aggregate"
	"github.com/sf9v/nero/comparison"
	"github.com/sf9v/nero/sort"
	"github.com/sf9v/nero/test/integration/user"
)

// PostgresRepository implements the Repository interface
type PostgresRepository struct {
	db     *sql.DB
	logger nero.Logger
	debug  bool
}

var _ Repository = (*PostgresRepository)(nil)

// NewPostgresRepository is a factory for PostgresRepository
func NewPostgresRepository(db *sql.DB) *PostgresRepository {
	return &PostgresRepository{
		db: db,
	}
}

// Debug enables debug mode
func (pg *PostgresRepository) Debug() *PostgresRepository {
	return &PostgresRepository{
		db:     pg.db,
		debug:  true,
		logger: log.New(os.Stdout, "nero: ", 0),
	}
}

// WithLogger overrides the default logger
func (pg *PostgresRepository) WithLogger(logger nero.Logger) *PostgresRepository {
	pg.logger = logger
	return pg
}

// Tx creates begins a new transaction
func (pg *PostgresRepository) Tx(ctx context.Context) (nero.Tx, error) {
	return pg.db.BeginTx(ctx, nil)
}

// Create creates a new User
func (pg *PostgresRepository) Create(ctx context.Context, c *Creator) (string, error) {
	return pg.create(ctx, pg.db, c)
}

// CreateTx creates a new User inside a transaction
func (pg *PostgresRepository) CreateTx(ctx context.Context, tx nero.Tx, c *Creator) (string, error) {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return "", errors.New("expecting tx to be *sql.Tx")
	}

	return pg.create(ctx, txx, c)
}

func (pg *PostgresRepository) create(ctx context.Context, runner nero.SQLRunner, c *Creator) (string, error) {
	if err := c.Validate(); err != nil {
		return "", err
	}

	columns := []string{
		"\"uid\"",
		"\"email\"",
		"\"name\"",
		"\"age\"",
		"\"group\"",
		"\"kv\"",
		"\"tags\"",
		"\"updated_at\"",
	}

	values := []interface{}{
		c.uid,
		c.email,
		c.name,
		c.age,
		c.group,
		c.kv,
		pq.Array(c.tags),
		c.updatedAt,
	}

	qb := squirrel.Insert("\"users\"").
		Columns(columns...).
		Values(values...).
		Suffix("RETURNING \"id\"").
		PlaceholderFormat(squirrel.Dollar).
		RunWith(runner)
	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: Create, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	var id string
	err := qb.QueryRowContext(ctx).Scan(&id)
	if err != nil {
		return "", err
	}

	return id, nil
}

// CreateMany creates many User
func (pg *PostgresRepository) CreateMany(ctx context.Context, cs ...*Creator) error {
	return pg.createMany(ctx, pg.db, cs...)
}

// CreateManyTx creates many User inside a transaction
func (pg *PostgresRepository) CreateManyTx(ctx context.Context, tx nero.Tx, cs ...*Creator) error {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return errors.New("expecting tx to be *sql.Tx")
	}

	return pg.createMany(ctx, txx, cs...)
}

func (pg *PostgresRepository) createMany(ctx context.Context, runner nero.SQLRunner, cs ...*Creator) error {
	if len(cs) == 0 {
		return nil
	}

	columns := []string{
		"\"uid\"",
		"\"email\"",
		"\"name\"",
		"\"age\"",
		"\"group\"",
		"\"kv\"",
		"\"tags\"",
		"\"updated_at\"",
	}
	qb := squirrel.Insert("\"users\"").Columns(columns...)
	for _, c := range cs {
		if err := c.Validate(); err != nil {
			return err
		}

		qb = qb.Values(
			c.uid,
			c.email,
			c.name,
			c.age,
			c.group,
			c.kv,
			pq.Array(c.tags),
			c.updatedAt,
		)
	}

	qb = qb.Suffix("RETURNING \"id\"").
		PlaceholderFormat(squirrel.Dollar)
	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: CreateMany, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	_, err := qb.RunWith(runner).ExecContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// Query queries many User
func (pg *PostgresRepository) Query(ctx context.Context, q *Queryer) ([]*user.User, error) {
	return pg.query(ctx, pg.db, q)
}

// QueryTx queries many User inside a transaction
func (pg *PostgresRepository) QueryTx(ctx context.Context, tx nero.Tx, q *Queryer) ([]*user.User, error) {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return nil, errors.New("expecting tx to be *sql.Tx")
	}

	return pg.query(ctx, txx, q)
}

func (pg *PostgresRepository) query(ctx context.Context, runner nero.SQLRunner, q *Queryer) ([]*user.User, error) {
	qb := pg.buildSelect(q)
	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: Query, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	rows, err := qb.RunWith(runner).QueryContext(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	users := []*user.User{}
	for rows.Next() {
		var user user.User
		err = rows.Scan(
			&user.ID,
			&user.UID,
			&user.Email,
			&user.Name,
			&user.Age,
			&user.Group,
			&user.Kv,
			pq.Array(&user.Tags),
			&user.UpdatedAt,
			&user.CreatedAt,
		)
		if err != nil {
			return nil, err
		}

		users = append(users, &user)
	}

	return users, nil
}

// QueryOne queries one User
func (pg *PostgresRepository) QueryOne(ctx context.Context, q *Queryer) (*user.User, error) {
	return pg.queryOne(ctx, pg.db, q)
}

// QueryOneTx queries one User inside a transaction
func (pg *PostgresRepository) QueryOneTx(ctx context.Context, tx nero.Tx, q *Queryer) (*user.User, error) {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return nil, errors.New("expecting tx to be *sql.Tx")
	}

	return pg.queryOne(ctx, txx, q)
}

func (pg *PostgresRepository) queryOne(ctx context.Context, runner nero.SQLRunner, q *Queryer) (*user.User, error) {
	qb := pg.buildSelect(q)
	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: QueryOne, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	var user user.User
	err := qb.RunWith(runner).
		QueryRowContext(ctx).
		Scan(
			&user.ID,
			&user.UID,
			&user.Email,
			&user.Name,
			&user.Age,
			&user.Group,
			&user.Kv,
			pq.Array(&user.Tags),
			&user.UpdatedAt,
			&user.CreatedAt,
		)
	if err != nil {
		return nil, err
	}

	return &user, nil
}

func (pg *PostgresRepository) buildSelect(q *Queryer) squirrel.SelectBuilder {
	columns := []string{
		"\"id\"",
		"\"uid\"",
		"\"email\"",
		"\"name\"",
		"\"age\"",
		"\"group\"",
		"\"kv\"",
		"\"tags\"",
		"\"updated_at\"",
		"\"created_at\"",
	}
	qb := squirrel.Select(columns...).
		From("\"users\"").
		PlaceholderFormat(squirrel.Dollar)

	pfs := q.pfs
	pb := &comparison.Predicates{}
	for _, pf := range pfs {
		pf(pb)
	}

	for _, p := range pb.All() {
		switch p.Op {
		case comparison.Eq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q = %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q = ?", p.Col), p.Arg)
			}
		case comparison.NotEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <> %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <> ?", p.Col), p.Arg)
			}
		case comparison.Gt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q > %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q > ?", p.Col), p.Arg)
			}
		case comparison.GtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q >= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q >= ?", p.Col), p.Arg)
			}
		case comparison.Lt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q < %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q < ?", p.Col), p.Arg)
			}
		case comparison.LtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <= ?", p.Col), p.Arg)
			}
		case comparison.IsNull:
			qb = qb.Where(fmt.Sprintf("%q IS NULL", p.Col))
		case comparison.IsNotNull:
			qb = qb.Where(fmt.Sprintf("%q IS NOT NULL", p.Col))
		case comparison.In, comparison.NotIn:
			args := p.Arg.([]interface{})
			if len(args) == 0 {
				continue
			}
			qms := []string{}
			for range args {
				qms = append(qms, "?")
			}
			fmtStr := "%q IN (%s)"
			if p.Op == comparison.NotIn {
				fmtStr = "%q NOT IN (%s)"
			}
			plchldr := strings.Join(qms, ",")
			qb = qb.Where(fmt.Sprintf(fmtStr, p.Col, plchldr), args...)
		}
	}

	sfs := q.sfs
	sorts := &sort.Sorts{}
	for _, sf := range sfs {
		sf(sorts)
	}
	for _, s := range sorts.All() {
		col := fmt.Sprintf("%q", s.Col)
		switch s.Direction {
		case sort.Asc:
			qb = qb.OrderBy(col + " ASC")
		case sort.Desc:
			qb = qb.OrderBy(col + " DESC")
		}
	}

	if q.limit > 0 {
		qb = qb.Limit(uint64(q.limit))
	}

	if q.offset > 0 {
		qb = qb.Offset(uint64(q.offset))
	}

	return qb
}

// Update updates User
func (pg *PostgresRepository) Update(ctx context.Context, u *Updater) (int64, error) {
	return pg.update(ctx, pg.db, u)
}

// UpdateTx updates User inside a transaction
func (pg *PostgresRepository) UpdateTx(ctx context.Context, tx nero.Tx, u *Updater) (int64, error) {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return 0, errors.New("expecting tx to be *sql.Tx")
	}

	return pg.update(ctx, txx, u)
}

func (pg *PostgresRepository) update(ctx context.Context, runner nero.SQLRunner, u *Updater) (int64, error) {
	qb := squirrel.Update("\"users\"").
		PlaceholderFormat(squirrel.Dollar)

	cnt := 0

	if !isZero(u.uid) {
		qb = qb.Set("\"uid\"", u.uid)
		cnt++
	}

	if !isZero(u.email) {
		qb = qb.Set("\"email\"", u.email)
		cnt++
	}

	if !isZero(u.name) {
		qb = qb.Set("\"name\"", u.name)
		cnt++
	}

	if !isZero(u.age) {
		qb = qb.Set("\"age\"", u.age)
		cnt++
	}

	if !isZero(u.group) {
		qb = qb.Set("\"group\"", u.group)
		cnt++
	}

	if !isZero(u.kv) {
		qb = qb.Set("\"kv\"", u.kv)
		cnt++
	}

	if !isZero(u.tags) {
		qb = qb.Set("\"tags\"", pq.Array(u.tags))
		cnt++
	}

	if !isZero(u.updatedAt) {
		qb = qb.Set("\"updated_at\"", u.updatedAt)
		cnt++
	}

	if cnt == 0 {
		return 0, nil
	}

	pfs := u.pfs
	pb := &comparison.Predicates{}
	for _, pf := range pfs {
		pf(pb)
	}

	for _, p := range pb.All() {
		switch p.Op {
		case comparison.Eq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q = %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q = ?", p.Col), p.Arg)
			}
		case comparison.NotEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <> %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <> ?", p.Col), p.Arg)
			}
		case comparison.Gt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q > %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q > ?", p.Col), p.Arg)
			}
		case comparison.GtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q >= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q >= ?", p.Col), p.Arg)
			}
		case comparison.Lt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q < %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q < ?", p.Col), p.Arg)
			}
		case comparison.LtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <= ?", p.Col), p.Arg)
			}
		case comparison.IsNull:
			qb = qb.Where(fmt.Sprintf("%q IS NULL", p.Col))
		case comparison.IsNotNull:
			qb = qb.Where(fmt.Sprintf("%q IS NOT NULL", p.Col))
		case comparison.In, comparison.NotIn:
			args := p.Arg.([]interface{})
			if len(args) == 0 {
				continue
			}
			qms := []string{}
			for range args {
				qms = append(qms, "?")
			}
			fmtStr := "%q IN (%s)"
			if p.Op == comparison.NotIn {
				fmtStr = "%q NOT IN (%s)"
			}
			plchldr := strings.Join(qms, ",")
			qb = qb.Where(fmt.Sprintf(fmtStr, p.Col, plchldr), args...)
		}
	}

	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: Update, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	res, err := qb.RunWith(runner).ExecContext(ctx)
	if err != nil {
		return 0, err
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}

	return rowsAffected, nil
}

// Delete deletes User
func (pg *PostgresRepository) Delete(ctx context.Context, d *Deleter) (int64, error) {
	return pg.delete(ctx, pg.db, d)
}

// Delete deletes User inside a transaction
func (pg *PostgresRepository) DeleteTx(ctx context.Context, tx nero.Tx, d *Deleter) (int64, error) {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return 0, errors.New("expecting tx to be *sql.Tx")
	}

	return pg.delete(ctx, txx, d)
}

func (pg *PostgresRepository) delete(ctx context.Context, runner nero.SQLRunner, d *Deleter) (int64, error) {
	qb := squirrel.Delete("\"users\"").
		PlaceholderFormat(squirrel.Dollar)

	pfs := d.pfs
	pb := &comparison.Predicates{}
	for _, pf := range pfs {
		pf(pb)
	}

	for _, p := range pb.All() {
		switch p.Op {
		case comparison.Eq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q = %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q = ?", p.Col), p.Arg)
			}
		case comparison.NotEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <> %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <> ?", p.Col), p.Arg)
			}
		case comparison.Gt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q > %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q > ?", p.Col), p.Arg)
			}
		case comparison.GtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q >= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q >= ?", p.Col), p.Arg)
			}
		case comparison.Lt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q < %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q < ?", p.Col), p.Arg)
			}
		case comparison.LtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <= ?", p.Col), p.Arg)
			}
		case comparison.IsNull:
			qb = qb.Where(fmt.Sprintf("%q IS NULL", p.Col))
		case comparison.IsNotNull:
			qb = qb.Where(fmt.Sprintf("%q IS NOT NULL", p.Col))
		case comparison.In, comparison.NotIn:
			args := p.Arg.([]interface{})
			if len(args) == 0 {
				continue
			}
			qms := []string{}
			for range args {
				qms = append(qms, "?")
			}
			fmtStr := "%q IN (%s)"
			if p.Op == comparison.NotIn {
				fmtStr = "%q NOT IN (%s)"
			}
			plchldr := strings.Join(qms, ",")
			qb = qb.Where(fmt.Sprintf(fmtStr, p.Col, plchldr), args...)
		}
	}

	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: Delete, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	res, err := qb.RunWith(runner).ExecContext(ctx)
	if err != nil {
		return 0, err
	}

	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}

	return rowsAffected, nil
}

// Aggregate runs aggregate operations
func (pg *PostgresRepository) Aggregate(ctx context.Context, a *Aggregator) error {
	return pg.aggregate(ctx, pg.db, a)
}

// Aggregate runs aggregate operations inside a transaction
func (pg *PostgresRepository) AggregateTx(ctx context.Context, tx nero.Tx, a *Aggregator) error {
	txx, ok := tx.(*sql.Tx)
	if !ok {
		return errors.New("expecting tx to be *sql.Tx")
	}

	return pg.aggregate(ctx, txx, a)
}

func (pg *PostgresRepository) aggregate(ctx context.Context, runner nero.SQLRunner, a *Aggregator) error {
	aggs := &aggregate.Aggregates{}
	for _, aggf := range a.aggfs {
		aggf(aggs)
	}
	cols := []string{}
	for _, agg := range aggs.All() {
		col := agg.Col
		qcol := fmt.Sprintf("%q", col)
		switch agg.Fn {
		case aggregate.Avg:
			cols = append(cols, "AVG("+qcol+") avg_"+col)
		case aggregate.Count:
			cols = append(cols, "COUNT("+qcol+") count_"+col)
		case aggregate.Max:
			cols = append(cols, "MAX("+qcol+") max_"+col)
		case aggregate.Min:
			cols = append(cols, "MIN("+qcol+") min_"+col)
		case aggregate.Sum:
			cols = append(cols, "SUM("+qcol+") sum_"+col)
		case aggregate.None:
			cols = append(cols, qcol)
		}
	}

	qb := squirrel.Select(cols...).From("\"users\"").
		PlaceholderFormat(squirrel.Dollar)

	groups := []string{}
	for _, group := range a.groups {
		groups = append(groups, fmt.Sprintf("%q", group.String()))
	}
	qb = qb.GroupBy(groups...)

	pfs := a.pfs
	pb := &comparison.Predicates{}
	for _, pf := range pfs {
		pf(pb)
	}

	for _, p := range pb.All() {
		switch p.Op {
		case comparison.Eq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q = %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q = ?", p.Col), p.Arg)
			}
		case comparison.NotEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <> %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <> ?", p.Col), p.Arg)
			}
		case comparison.Gt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q > %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q > ?", p.Col), p.Arg)
			}
		case comparison.GtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q >= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q >= ?", p.Col), p.Arg)
			}
		case comparison.Lt:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q < %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q < ?", p.Col), p.Arg)
			}
		case comparison.LtOrEq:
			col, ok := p.Arg.(Column)
			if ok {
				qb = qb.Where(fmt.Sprintf("%q <= %q", p.Col, col.String()))
			} else {
				qb = qb.Where(fmt.Sprintf("%q <= ?", p.Col), p.Arg)
			}
		case comparison.IsNull:
			qb = qb.Where(fmt.Sprintf("%q IS NULL", p.Col))
		case comparison.IsNotNull:
			qb = qb.Where(fmt.Sprintf("%q IS NOT NULL", p.Col))
		case comparison.In, comparison.NotIn:
			args := p.Arg.([]interface{})
			if len(args) == 0 {
				continue
			}
			qms := []string{}
			for range args {
				qms = append(qms, "?")
			}
			fmtStr := "%q IN (%s)"
			if p.Op == comparison.NotIn {
				fmtStr = "%q NOT IN (%s)"
			}
			plchldr := strings.Join(qms, ",")
			qb = qb.Where(fmt.Sprintf(fmtStr, p.Col, plchldr), args...)
		}
	}

	sfs := a.sfs
	sorts := &sort.Sorts{}
	for _, sf := range sfs {
		sf(sorts)
	}
	for _, s := range sorts.All() {
		col := fmt.Sprintf("%q", s.Col)
		switch s.Direction {
		case sort.Asc:
			qb = qb.OrderBy(col + " ASC")
		case sort.Desc:
			qb = qb.OrderBy(col + " DESC")
		}
	}

	if pg.debug && pg.logger != nil {
		sql, args, err := qb.ToSql()
		pg.logger.Printf("method: Aggregate, stmt: %q, args: %v, error: %v", sql, args, err)
	}

	rows, err := qb.RunWith(runner).QueryContext(ctx)
	if err != nil {
		return err
	}
	defer rows.Close()

	v := reflect.ValueOf(a.v).Elem()
	t := reflect.TypeOf(v.Interface()).Elem()
	if t.NumField() != len(cols) {
		return errors.New("aggregate columns and destination struct field count should match")
	}

	for rows.Next() {
		ve := reflect.New(t).Elem()
		dest := make([]interface{}, ve.NumField())
		for i := 0; i < ve.NumField(); i++ {
			dest[i] = ve.Field(i).Addr().Interface()
		}

		err = rows.Scan(dest...)
		if err != nil {
			return err
		}

		v.Set(reflect.Append(v, ve))
	}

	return nil
}
