// Code generated by nero, DO NOT EDIT.
package repository

import (
	"context"
	errors "github.com/pkg/errors"
	ksuid "github.com/segmentio/ksuid"
	nero "github.com/sf9v/nero"
	example "github.com/sf9v/nero/example"
	user "github.com/sf9v/nero/test/integration/user"
	"time"
)

// Repository is a User repository
type Repository interface {
	// Tx returns a transaction
	Tx(context.Context) (nero.Tx, error)
	// Create creates a User
	Create(context.Context, *Creator) (id string, err error)
	// CreateTx creates a User in a transaction
	CreateTx(context.Context, nero.Tx, *Creator) (id string, err error)
	// CreateMany creates Users
	CreateMany(context.Context, ...*Creator) error
	// CreateManyTx creates Users in a transaction
	CreateManyTx(context.Context, nero.Tx, ...*Creator) error
	// Query queries Users
	Query(context.Context, *Queryer) ([]*user.User, error)
	// QueryTx queries Users in a transaction
	QueryTx(context.Context, nero.Tx, *Queryer) ([]*user.User, error)
	// QueryOne queries a User
	QueryOne(context.Context, *Queryer) (*user.User, error)
	// QueryOneTx queries a User in a transaction
	QueryOneTx(context.Context, nero.Tx, *Queryer) (*user.User, error)
	// Update updates Users
	Update(context.Context, *Updater) (rowsAffected int64, err error)
	// UpdateTx updates Users in a transaction
	UpdateTx(context.Context, nero.Tx, *Updater) (rowsAffected int64, err error)
	// Delete deletes Users
	Delete(context.Context, *Deleter) (rowsAffected int64, err error)
	// Delete deletes User in a transaction
	DeleteTx(context.Context, nero.Tx, *Deleter) (rowsAffected int64, err error)
	// Aggregate aggregates Users
	Aggregate(context.Context, *Aggregator) error
	// Aggregate aggregates Users in a transaction
	AggregateTx(context.Context, nero.Tx, *Aggregator) error
}

// Creator is the create builder for User
type Creator struct {
	uid       ksuid.KSUID
	email     string
	name      string
	age       int
	group     user.Group
	kv        example.Map
	updatedAt *time.Time
}

// NewCreator returns a create builder
func NewCreator() *Creator {
	return &Creator{}
}

// UID is the setter for uid
func (c *Creator) UID(uid ksuid.KSUID) *Creator {
	c.uid = uid
	return c
}

// Email is the setter for email
func (c *Creator) Email(email string) *Creator {
	c.email = email
	return c
}

// Name is the setter for name
func (c *Creator) Name(name string) *Creator {
	c.name = name
	return c
}

// Age is the setter for age
func (c *Creator) Age(age int) *Creator {
	c.age = age
	return c
}

// Group is the setter for group
func (c *Creator) Group(group user.Group) *Creator {
	c.group = group
	return c
}

// Kv is the setter for kv
func (c *Creator) Kv(kv example.Map) *Creator {
	c.kv = kv
	return c
}

// UpdatedAt is the setter for updatedAt
func (c *Creator) UpdatedAt(updatedAt *time.Time) *Creator {
	c.updatedAt = updatedAt
	return c
}

// Query is the query builder for User
type Queryer struct {
	limit  uint64
	offset uint64
	pfs    []PredFunc
	sfs    []SortFunc
}

// NewQueryer returns a query builder
func NewQueryer() *Queryer {
	return &Queryer{}
}

// Where adds predicates to the query
func (q *Queryer) Where(pfs ...PredFunc) *Queryer {
	q.pfs = append(q.pfs, pfs...)
	return q
}

// Sort adds sort/order to the query
func (q *Queryer) Sort(sfs ...SortFunc) *Queryer {
	q.sfs = append(q.sfs, sfs...)
	return q
}

// Limit adds limit to the query
func (q *Queryer) Limit(limit uint64) *Queryer {
	q.limit = limit
	return q
}

// Offset adds offset to the query
func (q *Queryer) Offset(offset uint64) *Queryer {
	q.offset = offset
	return q
}

// Updater is the update builder for User
type Updater struct {
	uid       ksuid.KSUID
	email     string
	name      string
	age       int
	group     user.Group
	kv        example.Map
	updatedAt *time.Time
	pfs       []PredFunc
}

// NewUpdater returns an update builder
func NewUpdater() *Updater {
	return &Updater{}
}

// UID is the setter for uid
func (u *Updater) Uid(uid ksuid.KSUID) *Updater {
	u.uid = uid
	return u
}

// Email is the setter for email
func (u *Updater) Email(email string) *Updater {
	u.email = email
	return u
}

// Name is the setter for name
func (u *Updater) Name(name string) *Updater {
	u.name = name
	return u
}

// Age is the setter for age
func (u *Updater) Age(age int) *Updater {
	u.age = age
	return u
}

// Group is the setter for group
func (u *Updater) Group(group user.Group) *Updater {
	u.group = group
	return u
}

// Kv is the setter for kv
func (u *Updater) Kv(kv example.Map) *Updater {
	u.kv = kv
	return u
}

// UpdatedAt is the setter for updatedAt
func (u *Updater) UpdatedAt(updatedAt *time.Time) *Updater {
	u.updatedAt = updatedAt
	return u
}

// Where adds predicates to the query
func (u *Updater) Where(pfs ...PredFunc) *Updater {
	u.pfs = append(u.pfs, pfs...)
	return u
}

// Deleter is the delete builder for User
type Deleter struct {
	pfs []PredFunc
}

// NewDeleter returns a delete builder
func NewDeleter() *Deleter {
	return &Deleter{}
}

// Where adds predicates to the query
func (d *Deleter) Where(pfs ...PredFunc) *Deleter {
	d.pfs = append(d.pfs, pfs...)
	return d
}

// Aggregator is the aggregate builder for User
type Aggregator struct {
	v      interface{}
	aggfs  []AggFunc
	pfs    []PredFunc
	sfs    []SortFunc
	groups []Column
}

/*
NewAggregator takes a destination value (must be pointer
to slice of structs) and returns an aggregate builder
*/
func NewAggregator(v interface{}) *Aggregator {
	return &Aggregator{
		v: v,
	}
}

// Aggregate adds aggregate statements to the query
func (a *Aggregator) Aggregate(aggfs ...AggFunc) *Aggregator {
	a.aggfs = append(a.aggfs, aggfs...)
	return a
}

// Where adds predicates to the query
func (a *Aggregator) Where(pfs ...PredFunc) *Aggregator {
	a.pfs = append(a.pfs, pfs...)
	return a
}

// Sort adds sort/order to the query
func (a *Aggregator) Sort(sfs ...SortFunc) *Aggregator {
	a.sfs = append(a.sfs, sfs...)
	return a
}

// Group adds a grouping to the query
func (a *Aggregator) Group(cols ...Column) *Aggregator {
	a.groups = append(a.groups, cols...)
	return a
}

func rollback(tx nero.Tx, err error) error {
	rerr := tx.Rollback()
	if rerr != nil {
		err = errors.Wrapf(err, "rollback error: %v", rerr)
	}
	return err
}
