// Code generated by nero, DO NOT EDIT.
package user

import "time"

type Creator struct {
	collection string
	columns    []string
	email      *string
	name       *string
	age        int
	groupRes   string
	updatedAt  *time.Time
}

func NewCreator() *Creator {
	return &Creator{
		collection: collection,
		columns:    []string{"email", "name", "age", "group_res", "updated_at"},
	}
}

func (c *Creator) Email(email *string) *Creator {
	c.email = email
	return c
}

func (c *Creator) Name(name *string) *Creator {
	c.name = name
	return c
}

func (c *Creator) Age(age int) *Creator {
	c.age = age
	return c
}

func (c *Creator) GroupRes(groupRes string) *Creator {
	c.groupRes = groupRes
	return c
}

func (c *Creator) UpdatedAt(updatedAt *time.Time) *Creator {
	c.updatedAt = updatedAt
	return c
}
