// Code generated by nero, DO NOT EDIT.
package user

import (
	"context"
	errors "github.com/pkg/errors"
	ksuid "github.com/segmentio/ksuid"
	nero "github.com/sf9v/nero"
	example "github.com/sf9v/nero/example"
	user "github.com/sf9v/nero/test/integration/basic/user"
	"time"
)

// Repository is the contract for storing User
type Repository interface {
	Tx(context.Context) (nero.Tx, error)
	Create(context.Context, *Creator) (id string, err error)
	CreateTx(context.Context, nero.Tx, *Creator) (id string, err error)
	CreateMany(context.Context, ...*Creator) error
	CreateManyTx(context.Context, nero.Tx, ...*Creator) error
	Query(context.Context, *Queryer) ([]*user.User, error)
	QueryTx(context.Context, nero.Tx, *Queryer) ([]*user.User, error)
	QueryOne(context.Context, *Queryer) (*user.User, error)
	QueryOneTx(context.Context, nero.Tx, *Queryer) (*user.User, error)
	Update(context.Context, *Updater) (rowsAffected int64, err error)
	UpdateTx(context.Context, nero.Tx, *Updater) (rowsAffected int64, err error)
	Delete(context.Context, *Deleter) (rowsAffected int64, err error)
	DeleteTx(context.Context, nero.Tx, *Deleter) (rowsAffected int64, err error)
	Aggregate(context.Context, *Aggregator) error
	AggregateTx(context.Context, nero.Tx, *Aggregator) error
}

type Creator struct {
	uID       ksuid.KSUID
	email     string
	name      string
	age       int
	group     user.Group
	kv        example.Map
	updatedAt *time.Time
}

func NewCreator() *Creator {
	return &Creator{}
}

func (c *Creator) UID(uID ksuid.KSUID) *Creator {
	c.uID = uID
	return c
}

func (c *Creator) Email(email string) *Creator {
	c.email = email
	return c
}

func (c *Creator) Name(name string) *Creator {
	c.name = name
	return c
}

func (c *Creator) Age(age int) *Creator {
	c.age = age
	return c
}

func (c *Creator) Group(group user.Group) *Creator {
	c.group = group
	return c
}

func (c *Creator) Kv(kv example.Map) *Creator {
	c.kv = kv
	return c
}

func (c *Creator) UpdatedAt(updatedAt *time.Time) *Creator {
	c.updatedAt = updatedAt
	return c
}

type Queryer struct {
	limit  uint64
	offset uint64
	pfs    []PredFunc
	sfs    []SortFunc
}

func NewQueryer() *Queryer {
	return &Queryer{}
}

func (q *Queryer) Where(pfs ...PredFunc) *Queryer {
	q.pfs = append(q.pfs, pfs...)
	return q
}

func (q *Queryer) Sort(sfs ...SortFunc) *Queryer {
	q.sfs = append(q.sfs, sfs...)
	return q
}

func (q *Queryer) Limit(limit uint64) *Queryer {
	q.limit = limit
	return q
}

func (q *Queryer) Offset(offset uint64) *Queryer {
	q.offset = offset
	return q
}

type Updater struct {
	uID       ksuid.KSUID
	email     string
	name      string
	age       int
	group     user.Group
	kv        example.Map
	updatedAt *time.Time
	pfs       []PredFunc
}

func NewUpdater() *Updater {
	return &Updater{}
}

func (u *Updater) UID(uID ksuid.KSUID) *Updater {
	u.uID = uID
	return u
}

func (u *Updater) Email(email string) *Updater {
	u.email = email
	return u
}

func (u *Updater) Name(name string) *Updater {
	u.name = name
	return u
}

func (u *Updater) Age(age int) *Updater {
	u.age = age
	return u
}

func (u *Updater) Group(group user.Group) *Updater {
	u.group = group
	return u
}

func (u *Updater) Kv(kv example.Map) *Updater {
	u.kv = kv
	return u
}

func (u *Updater) UpdatedAt(updatedAt *time.Time) *Updater {
	u.updatedAt = updatedAt
	return u
}

func (u *Updater) Where(pfs ...PredFunc) *Updater {
	u.pfs = append(u.pfs, pfs...)
	return u
}

type Deleter struct {
	pfs []PredFunc
}

func NewDeleter() *Deleter {
	return &Deleter{}
}

func (d *Deleter) Where(pfs ...PredFunc) *Deleter {
	d.pfs = append(d.pfs, pfs...)
	return d
}

type Aggregator struct {
	v      interface{}
	aggfs  []AggFunc
	pfs    []PredFunc
	sfs    []SortFunc
	groups []Column
}

func NewAggregator(v interface{}) *Aggregator {
	return &Aggregator{
		v: v,
	}
}

func (a *Aggregator) Aggregate(aggfs ...AggFunc) *Aggregator {
	a.aggfs = append(a.aggfs, aggfs...)
	return a
}

func (a *Aggregator) Where(pfs ...PredFunc) *Aggregator {
	a.pfs = append(a.pfs, pfs...)
	return a
}

func (a *Aggregator) Sort(sfs ...SortFunc) *Aggregator {
	a.sfs = append(a.sfs, sfs...)
	return a
}

func (a *Aggregator) Group(cols ...Column) *Aggregator {
	a.groups = append(a.groups, cols...)
	return a
}

func rollback(tx nero.Tx, err error) error {
	rerr := tx.Rollback()
	if rerr != nil {
		err = errors.Wrapf(err, "rollback error: %v", rerr)
	}
	return err
}
