// Code generated by nero, DO NOT EDIT.
package user

import (
	"context"
	nero "github.com/sf9v/nero"
	user "github.com/sf9v/nero/test/integration/basic/user"
)

// Repository is the contract for storing User
type Repository interface {
	Tx(context.Context) (nero.Tx, error)
	Create(context.Context, *Creator) (id string, err error)
	CreateMany(context.Context, ...*Creator) error
	CreateTx(context.Context, nero.Tx, *Creator) (id string, err error)
	CreateManyTx(context.Context, nero.Tx, ...*Creator) error
	Query(context.Context, *Queryer) ([]*user.User, error)
	QueryOne(context.Context, *Queryer) (*user.User, error)
	QueryTx(context.Context, nero.Tx, *Queryer) ([]*user.User, error)
	QueryOneTx(context.Context, nero.Tx, *Queryer) (*user.User, error)
	Update(context.Context, *Updater) (rowsAffected int64, err error)
	UpdateTx(context.Context, nero.Tx, *Updater) (rowsAffected int64, err error)
	Delete(context.Context, *Deleter) (rowsAffected int64, err error)
	DeleteTx(context.Context, nero.Tx, *Deleter) (rowsAffected int64, err error)
	Aggregate(context.Context, *Aggregator) error
	AggregateTx(context.Context, nero.Tx, *Aggregator) error
}
