// Code generated by nero, DO NOT EDIT.
package user

import sort "github.com/sf9v/nero/sort"

// SortFunc is the sort function type
type SortFunc func(*sort.Sorts)

// Asc returns an ascending sort applied on column
func Asc(col Column) SortFunc {
	return func(srts *sort.Sorts) {
		srts.Add(&sort.Sort{
			Col:       col.String(),
			Direction: sort.Asc,
		})
	}
}

// Desc returns a descending sort applied on column
func Desc(col Column) SortFunc {
	return func(srts *sort.Sorts) {
		srts.Add(&sort.Sort{
			Col:       col.String(),
			Direction: sort.Desc,
		})
	}
}
