// Code generated by nero, DO NOT EDIT.
package user

import sort "github.com/sf9v/nero/sort"

type SortFunc func(*sort.Sorts)

func Asc(col Column) SortFunc {
	return func(srts *sort.Sorts) {
		srts.Add(&sort.Sort{
			Col:       col.String(),
			Direction: sort.Asc,
		})
	}
}

func Desc(col Column) SortFunc {
	return func(srts *sort.Sorts) {
		srts.Add(&sort.Sort{
			Col:       col.String(),
			Direction: sort.Desc,
		})
	}
}
