// Code generated by nero, DO NOT EDIT.
package user

import "time"

type Updater struct {
	collection string
	columns    []string
	email      *string
	name       *string
	age        int
	group      string
	updatedAt  *time.Time
	pfs        []PredFunc
}

func NewUpdater() *Updater {
	return &Updater{
		collection: collection,
		columns:    []string{"email", "name", "age", "group_res", "updated_at"},
	}
}

func (u *Updater) Email(email *string) *Updater {
	u.email = email
	return u
}

func (u *Updater) Name(name *string) *Updater {
	u.name = name
	return u
}

func (u *Updater) Age(age int) *Updater {
	u.age = age
	return u
}

func (u *Updater) Group(group string) *Updater {
	u.group = group
	return u
}

func (u *Updater) UpdatedAt(updatedAt *time.Time) *Updater {
	u.updatedAt = updatedAt
	return u
}

func (u *Updater) Where(pfs ...PredFunc) *Updater {
	u.pfs = append(u.pfs, pfs...)
	return u
}
