// Code generated by nero, DO NOT EDIT.
package user

import (
	uuid "github.com/google/uuid"
	user "github.com/sf9v/nero/test/integration/basic/user"
	"time"
)

type Updater struct {
	collection string
	columns    []string
	uID        uuid.UUID
	email      *string
	name       *string
	age        int
	group      user.Group
	updatedAt  *time.Time
	pfs        []PredFunc
}

func NewUpdater() *Updater {
	return &Updater{
		collection: collection,
		columns:    []string{"uid", "email", "name", "age", "group_res", "updated_at"},
	}
}

func (u *Updater) UID(uID uuid.UUID) *Updater {
	u.uID = uID
	return u
}

func (u *Updater) Email(email *string) *Updater {
	u.email = email
	return u
}

func (u *Updater) Name(name *string) *Updater {
	u.name = name
	return u
}

func (u *Updater) Age(age int) *Updater {
	u.age = age
	return u
}

func (u *Updater) Group(group user.Group) *Updater {
	u.group = group
	return u
}

func (u *Updater) UpdatedAt(updatedAt *time.Time) *Updater {
	u.updatedAt = updatedAt
	return u
}

func (u *Updater) Where(pfs ...PredFunc) *Updater {
	u.pfs = append(u.pfs, pfs...)
	return u
}
